### ISSUE TITLE
mpipy==3.0.3 requires ubuntu package `mpi-default-dev`

### ISSUE THREAD

**Issue by ghost** [BoyuanChen/neural-state-variables#1]
To install mpipy==3.0.3, I first needed to `sudo apt install mpi-default-dev`

https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/mpi-default-dev_1.13_amd64.deb.html

The clue during `pipenv install mpipy==3.0.3` was this:
```
_configtest.c:2:10: fatal error: mpi.h: No such file or directory                                 #include <mpi.h>
         ^~~~~~~
compilation terminated.
```

Might add this to system setup instructions?

**Comment by BoyuanChen** [comment]
Thanks for pointing this out! We will include this in our next release.
