### ISSUE TITLE
Question: there is a contradiction between code and paper

### ISSUE THREAD

**Issue by Sharp-rookie** [BoyuanChen/neural-state-variables#5]
In line 14 in analysis/intrinsic_dimension_estimation/methods.py, are the numerators and denominator written backwards?

def Levina_Bickel(X, dists, k):

    m = np.log(dists[:, k:k+1] / dists[:, 1:k])

    m = (k-2) / np.sum(m, axis=1) # this line

    dim = np.mean(m)

    return dim

**Comment by BoyuanChen** [comment]
There is a typo in the formula in the paper. Thanks for catching this! The code is correct.

The correct formula is as follows in the attached figure.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/22056953/206918014-68b93f01-34eb-4570-af41-86ca2d1c335b.png">
